### ISSUE TITLE
Error when running test script

### ISSUE THREAD

**Issue by glenndevenish** [vinayakkulkarni/nuxt-ava-e2e-unit-testing#5]
Steps:
1. Clone repository
2. Run `yarn`
3. Run `yarn test`

> [vue-test-utils]: window is undefined, vue-test-utils needs to be run in a browser environment.
    You can run the tests in node using jsdom
    See https://vue-test-utils.vuejs.org/guides/#browser-environment for more details.

Is there a misconfiguration with jsdom somewhere?

**Comment by glenndevenish** [comment]
The error only shows with the `test:unit` script, `test:e2e` runs fine

**Comment by vinayakkulkarni** [comment]
Hey @glenndevenish,

I had no issues with running `yarn test`, I tried with both Babel 6 (master branch) & Babel 7 (develop branch)

<img width="1665" alt="Screenshot 2019-04-15 at 7 44 27 PM" src="https://user-images.githubusercontent.com/19776877/56139664-ef00bb80-5fb6-11e9-8534-eb422fe26942.png">


### Maybe your node version is outdated?

```bash
$ node -v
v11.14.0
$ npm -v 
6.9.0
```

### Did you try to manually update the `test` script and change the `"test"` script?

```diff
- "test": "npm run test:unit & npm run test:e2e"
+ "test": "yarn run test:unit & yarn run test:e2e"
```

**Comment by vinayakkulkarni** [comment]
No reproducible output
